### ISSUE TITLE
User can search ingredients

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/recipeze#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can use the search bar and search up ingredients

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can type in the search bar and hit enter, page should not refresh but words in the search bar will disappear

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 1 - Search Ingredients](https://user-images.githubusercontent.com/95939062/163856201-d8ff0e88-4819-4825-be9c-5140d7ec249e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header, stickied so when it scrolls remains on top
- [x] create a div to hold form and hero image
- [x] Create form
- [x] create search input within form 
- [x] create a div underneath to separate the search bar from the future entries
- [x] make sure it is compatible for mobile view (width 375)
- [x] prevent page from refreshing when search bar is used
- [x] reset search bar after every search
- [x] create event listener for the search bar when entered
- [x] require entry in search bar before going through with search
- [x] parse search query and store as a variable
- [x] create a server request with the parameters given by the variable
- [x] store server response from search query as a variable
