### ISSUE TITLE
User can see recipes

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/recipeze#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view possible dishes according to their search query

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After typing ingredients into the search bar, the picture and name of recipes should populate at the bottom of the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Feature 2 - Create Search Entries](https://user-images.githubusercontent.com/95939062/163854944-05bc00c6-1d07-40b5-a7a5-1349a03f326f.png)

## ✅ Task List

- [x] create a container div to hold the search queries - give it a row space between class
- [x] for each result of the search query, give it a column third class
   - [x] use the entry name, id, and image to create an entry
   - [x] append the resulting dom tree to the page
- [x] create an event listener that encapsulates the buttons inside the searches
- [x] check to make sure CSS is not broken
- [x] check if mobile view still in working condition
- [x] searching again removes previous entries and adds new ones
