### ISSUE TITLE
User can get recipe info

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/recipeze#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get the recipe info

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A new page will pop up, populated with recipe information about the recipe selected (image of recipe, recipe name, serving size/ cook time, ingredient list, and instructions)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 3 - Recipe Info](https://user-images.githubusercontent.com/95939062/163856507-cd8e8460-38e4-4f9c-8f5b-a7145adbd86d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create new div for new recipe view
- [x] finish event listener for recipe info button
  - [x] get recipe Id assigned to each individual button
  - [x] assign the value to a new variable
- [x] create a new function to request for recipe information
  - [x] save server response as a variable
- [x]  check if information needed about recipe is able to be received
  - [x] create dom tree for information, append to new recipe view
- [x]  check if view swapping works
- [x] check css and mobile responsiveness to make sure it still works
- [x] add back button to return to previous view of searches
 - [x] create dom listener for the back button 
 - [x] make sure that it deconstructs the current dom tree for the recipe card 
 - [x] make sure view switches
