### ISSUE TITLE
User can add this recipe

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/recipeze#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add this recipe

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a button that saves the current recipe, the button changes color and changes text to added when the recipe is successfully added

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 4 - Add](https://user-images.githubusercontent.com/95939062/163857092-283e99db-ce0a-4a17-af1a-32d339b58462.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a button on the top right side to add entries
- [x] create event listener for the add entry button
 - [x] when button is clicked, button changes color (toggle later) and text to note that it has been added
- [x] create a new data object in data.js page to hold data entries
 - [x]  when button clicked, add recipe object to data object
 - [x] add local storage so data persists after page refresh
