### ISSUE TITLE
User can view a list of added recipes

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/recipeze#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of added recipes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A new button next to the logo allows the user to enter a new view of their saved recipes. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 5 - Saved Recipes](https://user-images.githubusercontent.com/95939062/163857576-2e910458-7e69-46c3-a4e0-4249bda6de4e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an entries view button in navbar 
- [x] create an entries view to view added recipes
- [x] rework dom tree generators to accept all object data in "recipe" format
  - [x] objects from data object should be able to be parsed in to create the "added" entries
  - [x] can click on recipe entries from saved recipe wage without having to make another server request
  - [x] add and unadd button retains functionality
- [x] ensure css and functionality maintained after changes
